### ISSUE TITLE
ShowList not working well for Redistribution Profiles

### ISSUE THREAD

**Issue by chadell** [PaloAltoNetworks/pango#52] opened 2021-01-18 13:50 UTC
## Describe the bug

`ShowList` of the redistribution profiles don't work well, returning an empty list when there is one created and failing when there is more than one.

## Expected behavior

`Client.Network.RedistributionProfile.ShowList(vrName)` should return a string slice of all the names of the redistribution profiles (IPv4)

## Current behavior

(describe the bug section)

## Possible solution

Debugging some queries I've observed that the function is using this XPATH (for Virtual  Router name test):

`"/config/devices/entry[@name='localhost.localdomain']/network/virtual-router/entry[@name='test']/protocol/redist-profile/entry/@name"`  and it gets:

* With only one redistribution profile: `<response status="success"><result> name="test"</result></response>`
* With two redistribution-profiles: `<response status="error"><msg><line>No such node</line></msg></response>`

Exploring the API browse for this XPATH `/config/devices/entry[@name='localhost.localdomain']/network/virtual-router/entry[@name='test']/protocol/redist-profile` I see the names are retrieved correctly.

My guess is that the `EntryListUsing` defined in https://github.com/PaloAltoNetworks/pango/blob/master/client.go#L214 is not taking into account in the `resp_struct` that this XPATH adds an extra label called `redist-profile`

![image](https://user-images.githubusercontent.com/15998111/104923454-5d4c8c00-599c-11eb-9877-97e4fe95fd94.png)

## Steps to reproduce

1. Create redistribution profiles
2. Run the ShowList function to get the PANGO objects
3.
4.

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3):
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by xhoms** [comment] 2021-01-18 14:48
Hi @shinmog,

may this be a duplicate of #29 ?

**Comment by shinmog** [comment] 2021-01-19 16:42
Yep, this is #29 - this namespace hasn't been updated yet.

**Closed** 2021-02-23 17:41 UTC
Labels: bug
