### ISSUE TITLE
ShowList returns No such node if no items present

### ISSUE THREAD

**Issue by megakoresh** [PaloAltoNetworks/pango#29] opened 2020-04-24 16:14 UTC
## Describe the bug

ShowList function returns nil instead of array and an error if items of that type are not available on the firewall. This is unlike GetList which simply returns an empty list in this case.

## Expected behavior

Empty list is returned like with GetList.

## Current behavior

`No such node` error is returned

## Possible solution

This seems to be an inconsistency in PaloAlto XML APIs (what a surprise...). Does it make sense to check for that error message and if it matches exactly, also return an empty array? Its what I am doing now in the code to mitigate this.

## Steps to reproduce

1. Don't add e.g. any Nat rules or Address Objects or PBF rules
2. Do `.ShowList(vsys)` on that object type
3. Observe `(~˘▾˘)~`

## Screenshots

N/A

## Context

Trying to extract running config from firewall.

## Your Environment

- Version used: 8.1.11
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Golang 1.13
- Operating System and version (desktop or mobile): CentOS 8
- Link to your project: Internal (for now)

UPDATE:
Apparently while the error comes from XML Api when there is no items, in some cases the library causes API to return that even when there are items available. For example for me it returns No such node when I try to query ethernet interfaces. When I use raw rest api, it works fine. Only library returns No node availble when using `ShowList`.

```sh
curl --location --request GET 'https://<firewall>/api/?type=config&action=show&key=$apikey&xpath=/config/devices/entry/network/interface/ethernet'
<some valid xml with no errors>
```

**Comment by shinmog** [comment] 2020-05-05 18:45
Ok, so...  I know that `get` and `show` work differently.  I think that the problem here is that I can't do an `@name` query when using `show`.  Looking at the pandevice code, it also checks for this and disallows doing `show` with `name_only`.

It seems like the fix for this is to only try and do `@name` queries if using `GetList`...  Should be a small code change to address this.

**Comment by megakoresh** [comment] 2020-05-05 19:59
> It seems like the fix for this is to only try and do @name queries if using GetList... Should be a small code change to address this.

I am not sure I understand this resolution, but if the change is indeed small, maybe you can do the PR? I don't have visibility into PanOS codebase so I don't know what's the "correct" solution to issues like that. But honestly it seems like a flaw in API. If those get and show are intended to be functionally equivalent, there must not be any behavioral differences.

**Comment by shinmog** [comment] 2020-05-05 22:14
Eeh, might have spoken too soon.  So, the fix is, "if `EntryListUsing()` is called with `client.Show`, don't append `@name` to the path variable."  Actually getting this answer without using `reflect` is feeling impossible..?  I can't type switch on the `fn` variable passed in because it's not an `interface{}`...

It's feeling like `EntryListUsing()` needs to be passed a string so I can make this decision, which means I have hundreds of lines of code to change...

**Comment by megakoresh** [comment] 2020-05-06 06:13
Why can't reflect be used? The performance impact is anyway negligible compared to the actual API call

**Comment by negorath** [comment] 2020-06-08 09:20
This issue isn't limited to `ShowList`, but also `ShowAll`. As you said, Show differs from Get in how it uses xpath, so in the case of `ShowAll` you would also have to remove the appended `/entry`.

**Comment by megakoresh** [comment] 2020-06-08 10:13
> This issue isn't limited to `ShowList`, but also `ShowAll`. As you said, Show differs from Get in how it uses xpath, so in the case of `ShowAll` you would also have to remove the appended `/entry`.

Well, I didn't experience this issue with ShowAll for some reason, even though the logic in your argument is solid. Have you tested and confirmed this behaviour?

**Comment by negorath** [comment] 2020-06-08 10:16
Yeah, the issue is what lead me to this post actually. When I try to run `ShowAll` for my post-rulebase policy list, it returns "No such node"; `GetAll` works fine.

**Comment by shinmog** [comment] 2020-06-11 21:32
Yeah, looks like ShowAll doesn't work...

Ok so, I guess now's as good a time as any.

I have been needing to redesign how namespaces function for a while now...  Not just to whole-sale fix this issue, but adding new namespaces is a very laborious task right now, and I know that even in a world where the language is statically typed, I should be able to abstract out a bit and DRY out this code a bit.  Fixing this issue will come along for the ride for this update.

**Comment by shinmog** [comment] 2020-07-11 06:12
@negorath @megakoresh 

Just finished fixing this issue for the `client.Policies.Security` namespace, the code in the various namespaces will now look like this going forward.  This also fixes the `ShowAll()` returning an error instead of gracefully handling it, and enables adding `GetAll()` / `ShowAll()` to all the other namespaces.

These updates also set the stage for retrieving sub objects from a parent object, just haven't implemented that yet (example:  doing `fw.Network.EthernetInterface.Get()` will allow you to retrieve layer3 subinterfaces / layer2 subinterfaces / arp entries / etc from that object).

In any case, I won't mark this fixed until I've converted all the rest of the namespaces.

**Closed** 2024-03-07 08:03 UTC
Labels: bug
